version: '3.9'
networks:
  frontend:
    external: true
services:
  cloudflare-tunnel:
    container_name: cloudflare-tunnel
    image: cloudflare/cloudflared:2023.8.2
    networks:
      - frontend
    restart: unless-stopped
    environment:
     - TUNNEL_TOKEN=$TUNNEL_TOKEN
    command: tunnel --no-autoupdate run
    
